---
abstract: 'save Gyazo like images to local'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  File::Temp: 0
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Plack-App-GyazoStocker
provides:
  Acme::Plack::App::GyazoStocker:
    file: lib/Acme/Plack/App/GyazoStocker.pm
    version: 0.03
requires:
  Carp: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Plack::App::File: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/bayashi/Acme-Plack-App-GyazoStocker/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Acme-Plack-App-GyazoStocker
version: 0.03
